### ISSUE TITLE
Update documentation for *.local.wholetale.org

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/deploy-dev#8]
Running latest from dev branch, the documentation is out of date. Need to remove references to vcap.me and add instructions for adding oath key/secret and certs.

**Comment by ThomasThelen** [comment]
I recently did a complete re-install of the dev system on Ubuntu. I think that the readme has since been updated to include 
1. Key/Secrets for Globus & ORCID
2. Adding traefik certs to the `acme` folder

I didn't see any references to vcap.me either, so this issue can probably be closed. Most of the changes were done [here](https://github.com/whole-tale/deploy-dev/commit/efa1861a4bcf2577d542f9fa28cd4b5e287f63b0)
